### ISSUE TITLE
android build dan pc standalone build lebih baik di ...........

### ISSUE THREAD

**Issue by stickylabdev** [fareezMaple/Tarbawi-2.0-quiz-Unity#1]
hapus saja ,,biar hemat kuota inet yg download

**Comment by iqfareez** [comment]
maksudnya apa? Mind to explain more?

**Comment by stickylabdev** [comment]
Saya menyarankan anda utk menghapus yg bukan source code .... Misal apk di hapus saja... Pp

**Comment by iqfareez** [comment]
Ohhh bisaa ajaa. Nnti saya ubah. Terima kasihh 🤗

**Comment by iqfareez** [comment]
done
